name: docker build

on:
  push:
    branches:
      - main
      - feature/multi-source
    paths-ignore:
      - LICENSE
      - 'README.*'
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

# permissions are needed if pushing to ghcr.io
permissions:
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: linux/amd64
            os: ubuntu-latest
            buildfile: ubuntu
            base_image: ghcr.io/asamk/signal-cli
            source: project

          - platform: linux/amd64
            os: ubuntu-latest
            buildfile: ubuntu
            base_image: registry.gitlab.com/packaging/signal-cli/signal-cli-jre
            source: community
          - platform: linux/arm64
            os: ubuntu-24.04-arm
            buildfile: ubuntu
            base_image: registry.gitlab.com/packaging/signal-cli/signal-cli-jre
            source: community

          - platform: linux/amd64
            os: ubuntu-latest
            buildfile: alpine
            base_image: alpine
            source: distro
          - platform: linux/arm64
            os: ubuntu-24.04-arm
            buildfile: alpine
            base_image: alpine
            source: distro

          - platform: linux/amd64
            os: ubuntu-latest
            buildfile: alpine
            base_image: alpine
            source: project
          - platform: linux/arm64
            os: ubuntu-24.04-arm
            buildfile: alpine
            base_image: alpine
            source: project

    steps:
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >>"${GITHUB_ENV}"
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push by digest
        id: build
        uses: docker/build-push-action@v7
        with:
          context: image
          file: image/Dockerfile.${{ matrix.buildfile }}
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            SOURCE=${{ matrix.source }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
      -
        name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      -
        name: Upload digest
        uses: actions/upload-artifact@v7
        with:
          name: digests-${{ matrix.buildfile }}-${{ matrix.source }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: true
      matrix:
        buildfile: [ubuntu, alpine]
        source: [project, community, distro]
        exclude:
          - buildfile: ubuntu
            source: distro
          - buildfile: alpine
            source: community
    steps:
      -
        name: Download digests
        uses: actions/download-artifact@v8
        with:
          path: /tmp/digests
          pattern: digests-${{ matrix.buildfile }}-${{ matrix.source }}*
          merge-multiple: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + . + "-${{ matrix.buildfile }}-${{ matrix.source }}") | join(" ")' <<< "${DOCKER_METADATA_OUTPUT_JSON}") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
